"""add_changes_count

Revision ID: 954fa84e6c85
Revises: a08e5d7df6a5
Create Date: 2026-07-05 01:51:46.754346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '954fa84e6c85'
down_revision: Union[str, Sequence[str], None] = 'a08e5d7df6a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('allocations', sa.Column('changes_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('allocations', 'changes_count')
    # ### end Alembic commands ###
